[package]
name = "greeting-as-a-service"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.7"
serde = "1.0.136"
serde_json = "1.0.93"

tokio = { version = "1", features = ["macros"] }

# CloudWatch logging
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }